// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCinGUjaHXSfQQRTikbcGA6cJz6eoXtKXU',
    appId: '1:1021883255891:web:e9827fa85492225ab1caa6',
    messagingSenderId: '1021883255891',
    projectId: 'ulearning-app-19a09',
    authDomain: 'ulearning-app-19a09.firebaseapp.com',
    storageBucket: 'ulearning-app-19a09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBokJXtOd2sl6faHkOPp7Xn0ddnCe7iYNI',
    appId: '1:1021883255891:android:4c7b1078b25b423db1caa6',
    messagingSenderId: '1021883255891',
    projectId: 'ulearning-app-19a09',
    storageBucket: 'ulearning-app-19a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwMaM8gn1bgO4GuHbIQ9DMIDOaX-hS9o0',
    appId: '1:1021883255891:ios:ea0dfdde38507960b1caa6',
    messagingSenderId: '1021883255891',
    projectId: 'ulearning-app-19a09',
    storageBucket: 'ulearning-app-19a09.appspot.com',
    iosClientId: '1021883255891-mmsi0utgrhet1gb11ic5bst11t65sj6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwMaM8gn1bgO4GuHbIQ9DMIDOaX-hS9o0',
    appId: '1:1021883255891:ios:ea0dfdde38507960b1caa6',
    messagingSenderId: '1021883255891',
    projectId: 'ulearning-app-19a09',
    storageBucket: 'ulearning-app-19a09.appspot.com',
    iosClientId: '1021883255891-mmsi0utgrhet1gb11ic5bst11t65sj6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulearn',
  );
}
